site_name: Matt Teeter
site_author: Matt Teeter
site_description: >-
  Matt Teeter's personal 'portfolio' site.

plugins:
  - git-revision-date-localized
  - tags
  - blog

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/solid/code
  favicon: images/favicon.png
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/matt328
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matt-t-225902252

nav:
  - About: index.md
  - Projects:
      - Triton: triton.md
      - Bootstrap: bootstrap.md
      - Cashbox: cashbox.md
  - Blog:
      - blog/index.md
